name: tekora_app_absensi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.10.8


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^21.0.0
  geocoding: ^3.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.17.0
  http: ^1.6.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  timezone: ^0.11.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_apk.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_apk.png"


flutter:


  uses-material-design: true

  assets:
    - assets/images/
